### ISSUE TITLE
Not compatible with should 4.4?

### ISSUE THREAD

**Issue by daiheitan** [myndzi/should-eventually#1] opened 2015-01-07 09:34 UTC
peerdependency of should out of data now.

**Comment by myndzi** [comment] 2015-01-07 15:10
Yeah, peer dependencies are BS, not very useful. I set it at 4.0 to at least alert people that things were awry in newer versions. I've yet to have a chance to work out why and fix it, but that's half because I didn't realize anyone cared :)

**Comment by myndzi** [comment] 2015-01-07 19:19
I appear unable to reproduce the problem I had, so I've released the peerDependency restriction to ^4.0.0

Please report it if you encounter some problem; this package is a bit unstable because it messes with should.js internals. Closing in the meantime.

**Closed by myndzi** 2015-01-07 19:19 UTC

**Comment by daiheitan** [comment] 2015-01-08 01:30
After opened this issue I found that Should.js has its own promise module:

https://github.com/shouldjs/promised

However, the module's features are very limited.
